project:
  type: website
  output-dir: docs

website:
  title: "Nelly Tkachman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tidytuesday.qmd
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



